### ISSUE TITLE
Component with id [1] does not exist.

### ISSUE THREAD

**Issue by LowBoBYT** [mtakaki/cachet-url-monitor#115]
Hello,

I'm getting the error 'Component with id does not exist.', are my settings wrong? 

best regards
![Screenshot_46](https://user-images.githubusercontent.com/63642989/102485003-4fd37780-4067-11eb-9a98-625b4b040c7d.png)

**Comment by InFerYes** [comment]
On the cachet dashboard, do you have a component with ID 1?

In the dashboard you can edit the components and see the ID in the URL e.g. https//_baseurl_/dashboard/components/**1**/edit

**Comment by jfrancosre** [comment]
I am facing similar issue, however I am able to verify that the component id is available, I am able to cURL from the virtual env as well. What else could be wrong here @InFerYes

**Comment by jfrancosre** [comment]
also @mtakaki

**Comment by jfrancosre** [comment]
I get the following error
Traceback (most recent call last):
  File "cachet_url_monitor/scheduler.py", line 160, in <module>
    configuration = Configuration(config_data, endpoint_index, client, webhooks)
  File "/opt/cachet-url-monitor/venv/lib/python3.6/site-packages/cachet_url_monitor-0.6.11-py3.6.egg/cachet_url_monitor/configuration.py", line 105, in __init__
    self.status = self.client.get_component_status(self.component_id)
  File "/opt/cachet-url-monitor/venv/lib/python3.6/site-packages/cachet_url_monitor-0.6.11-py3.6.egg/cachet_url_monitor/client.py", line 84, in get_component_status
    raise exceptions.ComponentNonexistentError(component_id)
cachet_url_monitor.exceptions.ComponentNonexistentError: 'Component with id [6] does not exist.'

**Comment by jfrancosre** [comment]
Any help is highly appreciated

**Comment by joker-119** [comment]
Same issue here

**Comment by joker-119** [comment]
I resolved this issue for me, it was because CF verification page was being returned instead of the actual API, I needed to remove proxy from CF on the dns record for cachet
