### ISSUE TITLE
Trailing slash in api_url causes 404

### ISSUE THREAD

**Issue by gardner** [mtakaki/cachet-url-monitor#18]
Removing the trailing slash from the config file fixes this.

Ubuntu Linux 16
Python: 2.7

```
<Response [404]>
Traceback (most recent call last):
  File "cachet_url_monitor/scheduler.py", line 77, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "cachet_url_monitor/scheduler.py", line 50, in __init__
    self.configuration = Configuration(config_file)
  File "/home/gardner/cachet-url-monitor/cachet_url_monitor/configuration.py", line 84, in __init__
    self.status = get_current_status(self.api_url, self.component_id, self.headers)
  File "/home/gardner/cachet-url-monitor/cachet_url_monitor/configuration.py", line 56, in get_current_status
    raise ComponentNonexistentError(component_id)
configuration.ComponentNonexistentError: 'Component with id [1] does not exist.'

```

**Comment by gardner** [comment]
Thanks for pulling this in
