### ISSUE TITLE
Expectation validation is not working properly

### ISSUE THREAD

**Issue by mtakaki** [mtakaki/cachet-url-monitor#21]
When creating a config, if the expectation is not a valid option is just fail with a non-descriptive exception:

```
Traceback (most recent call last):
  File "cachet_url_monitor/scheduler.py", line 54, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "cachet_url_monitor/scheduler.py", line 32, in __init__
    self.configuration = Configuration(config_file)
  File "/usr/src/app/cachet_url_monitor/configuration.py", line 43, in __init__
    in self.data['endpoint']['expectation']]
  File "/usr/src/app/cachet_url_monitor/configuration.py", line 152, in create
    return expectations.get(configuration['type'])(configuration)
TypeError: 'NoneType' object is not callable
```

It should also list the available options.

**Comment by mtakaki** [comment]
This is fixed by #77
