### ISSUE TITLE
Error :(

### ISSUE THREAD

**Issue by niclasreich** [mtakaki/cachet-url-monitor#37]
```
(cachet-url-monitor)root@244637a1:/opt/cachet-url-monitor# python cachet_url_monitor/scheduler.py config.yml
     INFO [2017-03-14 18:03:29,590] cachet_url_monitor.configuration.Configuration - Current configuration:
cachet:
  action:
  - CREATE_INCIDENT
  - UPDATE_STATUS
  api_url: https://status.PAGE.eu/api/v1
  component_id: 3
  public_incidents: true
endpoint:
  expectation:
  - status: 200
    type: HTTP_STATUS
  - threshold: 1
    type: LATENCY
  - regex: .*(<body).*
    type: REGEX
  method: GET
  timeout: 1
  url: https://PAGE.eu
frequency: 30

Traceback (most recent call last):
  File "cachet_url_monitor/scheduler.py", line 89, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "cachet_url_monitor/scheduler.py", line 55, in __init__
    self.configuration = Configuration(config_file)
  File "/opt/cachet-url-monitor/cachet_url_monitor/configuration.py", line 91, in __init__
    self.default_metric_value = self.get_default_metric_value()
  File "/opt/cachet-url-monitor/cachet_url_monitor/configuration.py", line 107, in get_default_metric_value
    return get_metric_request.json()['data']['default_value']
KeyError: 'data'
(cachet-url-monitor)root@244637a1:/opt/cachet-url-monitor# 
```

**Comment by mtakaki** [comment]
This is related to #34 changes. Please use the tagged latest release, as it's a stable release. Or you could also use the docker image.

I'll look into this whenever I get free as the build is currently broken too.

**Comment by ImFlushy** [comment]
Thanks - amazingly working fine now.
Is there a way to change the output-text to something custom? Already tried some editing but couldn't get it to work.

**Comment by ImFlushy** [comment]
Is there any way to run this in background? E.g. with screen?

**Comment by mtakaki** [comment]
One year later... Could you please confirm if this issue still happens to you with the latest code?
I fixed the build and I ran some manual tests, it seems to be working fine.

I'm really sorry about the huge delay to fix this.

**Comment by niclasreich** [comment]
Hi,
seems to work now. Thanks for your follow-up!
