### ISSUE TITLE
NameError: name 'file' is not defined

### ISSUE THREAD

**Issue by jayze** [mtakaki/cachet-url-monitor#68]
Hi,

I've installed the package via pip, when adding the config.yml file and starting it via : python3 scheduler.py config.yml I get the following error message :

Traceback (most recent call last):
  File "scheduler.py", line 89, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "scheduler.py", line 55, in __init__
    self.configuration = Configuration(config_file)
  File "/usr/local/lib/python3.7/site-packages/cachet_url_monitor/configuration.py", line 83, in __init__
    self.data = load(file(self.config_file, 'r'))
NameError: name 'file' is not defined

any idea how to solve this?

Jay

**Comment by mtakaki** [comment]
I'm closing this ticket, as I haven't gotten an answer in 15 days. Please, feel free to re-open it if it's still happening for you.
